# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 102e0b68d8803131746b58acf42ef7b063991f38973e7fc15907d5275688eab7ef9b2af9e53522ef4f8245a568a43261f450fd1404e7399a405d55d05ea62e6a

test:
  secret_key_base: ce41486bb1e8e59e3c81f2e097cd2d97ad5782e451e6dbf53111f01a68a628bdb22a37ef82ad75002cc25442971bfb877f3c3df4c64bb9d0e0fd8c1cdb14259e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
